### PR TITLE
Add IDEA project

### PR DESCRIPTION
**Pull request by aknuds1**
Added IDEA project generated through [SBT IDEA plugin](https://github.com/mpeltonen/sbt-idea). Made a best effort stab at configuring .gitignore correctly. Not sure yet how to build from IDEA though.

### CODE REVIEW

**Comment by freekh** [comment]
Hey Arve! Thanks for this PR! 
Should the .idea dir be in there or should it not?

**Comment by aknuds1** [comment]
My impression (from initial research) is that the .idea contents (excepting what is in .gitignore) are necessary unless every developer should regenerate the project. Being new to sbt and IDEA I'm not sure what is the correct approach, but I'm used to relevant project settings being shared via source control, not sure how to accomplish this without sharing .idea contents.

**Comment by freekh** [comment]
Right, I guess it was you said earlier - I was just under the impression it should not be there so I was just wondering.

**Comment by aknuds1** [comment]
Yeah it's a bit confusing. Hopefully we'll find out with experience. I'm hoping the IDEA project can more or less keep itself in sync without having to be re-generated in the future.

**Comment by freekh** [comment]
Yup, that would be ideal - not a hard thing to remove either way.

I guess it would be nice to thank you for the PR as well so thanks :) and have a good evening!

Hope there will be more adepting going on :)

**Pull request merged**
